name: Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hacs:
    name: HACS
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"

  hass:
    name: Home Assistant
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Home Assistant validation
        uses: "home-assistant/actions/hass-action@main"
        with:
          path: "./custom_components/tibber_grid_reward"
