name: Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hacs:
    name: HACS
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"

  hassfest:
    name: Hassfest
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Run hassfest
        uses: "home-assistant/actions/hassfest@master"

  linter:
    name: Linter
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Set up Python
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt
      - name: Run linter
        run: ruff check .

  tests:
    name: Tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Set up Python
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt
      - name: Run tests
        run: pytest