name: Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hacs:
    name: HACS
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
          ignore: "brands license"

  hassfest:
    name: Hassfest
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
      - name: Run hassfest
        # Awaiting maintained release tags: https://github.com/home-assistant/actions/issues/144
        uses: "home-assistant/actions/hassfest@58bff37c8947f690ace498be413a9b78d6f30f93"

  linter:
    name: Linter
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
      - name: Set up Python
        uses: "actions/setup-python@v7"
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt
      - name: Run linter
        run: ruff check .

  tests:
    name: Tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
      - name: Set up Python
        uses: "actions/setup-python@v7"
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt
      - name: Run tests
        run: pytest