name: Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hacs:
    name: HACS
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"

  hassfest:
    name: Hassfest
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Set up Python
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: Run hassfest
        run: |
          pip install homeassistant
          python -m homeassistant.scripts.hassfest -p custom_components/tibber_grid_reward

  tests:
    name: Tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Set up Python
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r custom_components/tibber_grid_reward/requirements.txt
          pip install pytest httpx
      - name: Run tests
        run: pytest custom_components/tibber_grid_reward/tests